import {
  copyTemplate,
  readConfigFile,
  runGenerator,
  runValidator,
  runSolution,
} from './helpers';
import { logger } from './logger';
import path from 'path';
import fs from 'fs';

export const createTemplate = (directory: string) => {
  // const spinner = logger.startSpinner('Creating problem template...');
  logger.info('Creating problem template...');
  try {
    const pwd = process.cwd();
    const problemDir = path.resolve(pwd, directory);
    const templateDir = path.resolve(__dirname, '../template');

    fs.mkdirSync(problemDir, { recursive: true });
    copyTemplate(templateDir, problemDir);

    // spinner.succeed(
    //   `Template created successfully at ${logger.highlight(directory)}`
    // );
    logger.info(`Next steps:`);
    logger.log(`  1. cd ${directory}`);
    logger.log(`  2. Edit config.json to configure your problem`);
    logger.log(`  3. Run ${logger.highlight('polyman generate-tests')}`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    // spinner.fail('Failed to create template');
    logger.error(message);
    process.exit(1);
  }
};

export const generateTests = async (generatorName: string) => {
  logger.section('Test Generation');

  try {
    const { generators } = readConfigFile();
    if (!generators || generators.length === 0) {
      logger.warning('No test generators defined in the configuration file.');
      return;
    }

    logger.info(`Found ${generators.length} generator(s)`);

    for (const generator of generators) {
      if (generator.name === generatorName || generatorName === 'all') {
        await runGenerator(generator);
      }
    }

    logger.success('All test cases generated successfully!');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to generate tests: ${message}`);
    process.exit(1);
  }
};

export const validateTests = async (arg: string) => {
  logger.section('Test Validation');

  try {
    const config = readConfigFile();
    if (!config.validator) {
      throw new Error('No validator defined in the configuration file.');
    }

    if (arg === 'all') {
      await runValidator(config.validator);
      logger.success('All tests validated successfully!');
    } else {
      const testNumber = parseInt(arg, 10);
      if (!isNaN(testNumber)) {
        await runValidator(config.validator, testNumber, testNumber);
        logger.success(`Test ${testNumber} validated successfully!`);
      } else {
        const generator = config.generators?.find(g => g.name === arg);
        if (!generator) {
          throw new Error(
            `No generator named "${arg}" found in the configuration file.`
          );
        }
        const [start, end] = generator['tests-range'];
        await runValidator(config.validator, start, end);
        logger.success(`Tests generated by "${arg}" validated successfully!`);
      }
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to validate tests: ${message}`);
    process.exit(1);
  }
};

export const solveTests = async (solutionName: string, arg: string) => {
  logger.section(`Running Solution: ${solutionName}`);

  try {
    const config = readConfigFile();
    if (!config.solutions || config.solutions.length === 0) {
      throw new Error('No solutions defined in the configuration file.');
    }
    let found = false;
    if (arg === 'all') {
      for (const solution of config.solutions) {
        if (solution.name === solutionName || solutionName === 'all') {
          found = true;
          await runSolution(
            solution,
            config['time-limit'],
            config['memory-limit']
          );
        }
      }
    } else {
      const testNumber = parseInt(arg, 10);
      if (!isNaN(testNumber)) {
        for (const solution of config.solutions) {
          if (solution.name === solutionName || solutionName === 'all') {
            found = true;
            await runSolution(
              solution,
              config['time-limit'],
              config['memory-limit'],
              testNumber,
              testNumber
            );
          }
        }
      } else {
        const generator = config.generators?.find(g => g.name === arg);
        if (!generator) {
          throw new Error(
            `No generator named "${arg}" found in the configuration file.`
          );
        }
        const [start, end] = generator['tests-range'];
        for (const solution of config.solutions) {
          if (solution.name === solutionName || solutionName === 'all') {
            found = true;
            await runSolution(
              solution,
              config['time-limit'],
              config['memory-limit'],
              start,
              end
            );
          }
        }
      }
    }

    if (!found) {
      throw new Error(
        `Solution named "${solutionName}" not found or no solutions defined.`
      );
    }

    logger.success('Solutions run completed successfully!');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    logger.error(`Failed to run solution: ${message}`);
    process.exit(1);
  }
};
